services:
  postgres:
    image: "postgres:16.3-alpine3.20"
    environment:
      - "POSTGRES_DB=runners"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=ben"
    ports:
      - "5434:5432"
